/*
 * Copyright (c) 2024, Renesas Electronics Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/** 
 * @file  W25N01GVZEIG.h
 * @brief SPI NAND W25N01GVZEIG's command and register definitions.
 *
 */

#ifndef __SPI_NAND_W25N01GVZEIG_H__
#define __SPI_NAND_W25N01GVZEIG_H__

#ifdef __cplusplus
extern "C"
{
#endif

/* ************************ HEADER (INCLUDE) SECTION *********************** */
/* ***************** MACROS, CONSTANTS, COMPILATION FLAGS ****************** */

/** @brief Command Set - Standard Operation
 */
#define SPI_NAND_CMD_DEVICE_RESET				(0xFF)
#define SPI_NAND_CMD_JEDEC_ID					(0x9F)
#define SPI_NAND_CMD_READ_STATUS_REGISTER		(0x0F)
#define SPI_NAND_CMD_WRITE_STATUS_REGISTER		(0x1F)
#define SPI_NAND_CMD_WRITE_ENABLE				(0x06)
#define SPI_NAND_CMD_WRITE_DISABLE				(0x04)
#define SPI_NAND_CMD_BLOCK_ERASE				(0xD8)
#define SPI_NAND_CMD_PROGRAM_DATA_LOAD			(0x02)
#define SPI_NAND_CMD_QUAD_PROGRAM_DATA_LOAD		(0x32)
#define SPI_NAND_CMD_PROGRAM_EXECUTE			(0x10)
#define SPI_NAND_CMD_PAGE_DATA_READ				(0x13)
#define SPI_NAND_CMD_READ						(0x03)
#define SPI_NAND_CMD_FAST_READ_QUAD_IO			(0xEB)

/** @brief Register Address
 */
#define SPI_NAND_SR_ADD_PROTECTION_REGISTER		(0xA0)
#define SPI_NAND_SR_ADD_CONFIGURATION_REGISTER	(0xB0)
#define SPI_NAND_SR_ADD_STATUS_REGISTER			(0xC0)

/** @brief Protection Register Definitions
 */
#define SPI_NAND_REG_PROTECTION_BP_POS			(3)
#define SPI_NAND_REG_PROTECTION_BP_POS_LOCKED	(15u)
#define SPI_NAND_REG_PROTECTION_BP_POS_UNLOCKED	(0u)
#define SPI_NAND_REG_PROTECTION_BP				(SPI_NAND_REG_PROTECTION_BP_POS_LOCKED << SPI_NAND_REG_PROTECTION_BP_POS)

/** @brief Configuration Register Definitions
 */
#define SPI_NAND_REG_CONFIGURATION_ECC_POS		(4)
#define SPI_NAND_REG_CONFIGURATION_ECC_ENABLE	(1u)
#define SPI_NAND_REG_CONFIGURATION_ECC_DISABLE	(0u)
#define SPI_NAND_REG_CONFIGURATION_ECC			(SPI_NAND_REG_CONFIGURATION_ECC_ENABLE << SPI_NAND_REG_CONFIGURATION_ECC_POS)
#define SPI_NAND_REG_CONFIGURATION_BUF_POS		(3)
#define SPI_NAND_REG_CONFIGURATION_BUF_ENABLE	(1u)
#define SPI_NAND_REG_CONFIGURATION_BUF_DISABLE	(0u)
#define SPI_NAND_REG_CONFIGURATION_BUF			(SPI_NAND_REG_CONFIGURATION_BUF_ENABLE << SPI_NAND_REG_CONFIGURATION_BUF_POS)

/** @brief Status Register Definitions
 */
#define SPI_NAND_REG_STATUS_ECC_POS			(4)
#define SPI_NAND_REG_STATUS_ECC_NO_ERROR	(0u)
#define SPI_NAND_REG_STATUS_ECC_1BIT_ERROR	(1u)
#define SPI_NAND_REG_STATUS_ECC_2BIT_SINGLE	(2u)
#define SPI_NAND_REG_STATUS_ECC_2BIT_MULTI	(3u)
#define SPI_NAND_REG_STATUS_ECC				(SPI_NAND_REG_STATUS_ECC_2BIT_MULTI << SPI_NAND_REG_STATUS_ECC_POS)
#define SPI_NAND_REG_STATUS_P_FAIL_POS		(3)
#define SPI_NAND_REG_STATUS_P_FAIL			(1u << SPI_NAND_REG_STATUS_P_FAIL_POS)
#define SPI_NAND_REG_STATUS_E_FAIL_POS		(2)
#define SPI_NAND_REG_STATUS_E_FAIL			(1u << SPI_NAND_REG_STATUS_E_FAIL_POS)
#define SPI_NAND_REG_STATUS_WEL_POS			(1)
#define SPI_NAND_REG_STATUS_WEL				(1u << SPI_NAND_REG_STATUS_WEL_POS)
#define SPI_NAND_REG_STATUS_BUSY_POS		(0)
#define SPI_NAND_REG_STATUS_BUSY			(1u << SPI_NAND_REG_STATUS_BUSY_POS)

/** @brief RADD Definitions
 */
#define SPI_NAND_RADD_BLOCK_ADDRESS_POS		(6)

/** @brief Wait Ready Time Definitions
 */
#define SPI_NAND_TIME_WAIT_READY_RESET					(1000)
#define SPI_NAND_TIME_WAIT_READY_PAGE_READ				(100)
#define SPI_NAND_TIME_WAIT_READY_ERASE_BLOCK			(6000)
#define SPI_NAND_TIME_WAIT_READY_PAGE_PROGRAM			(1000)
#define SPI_NAND_TIME_WAIT_READY_WRITE_ENABLE_DISABLE	(100)

/** @brief Target SPI NAND ID
 */
#define SPI_NAND_MANUFACTURER_ID		(0xEF)
#define SPI_NAND_DEVICE_ID				(0xAA21)

/** @brief Target SPI NAND Features
 */
#define SPI_NAND_NUM_OF_BLOCKS			(1024U)
#define SPI_NAND_NUM_OF_PAGES_IN_BLOCK	(64U)
#define SPI_NAND_PAGE_MAIN_BYTES		(2048U)
#define SPI_NAND_PAGE_SPARE_BYTES		(64U)
#define SPI_NAND_BLOCK_BYTES			(SPI_NAND_PAGE_MAIN_BYTES*SPI_NAND_NUM_OF_PAGES_IN_BLOCK)
#define SPI_NAND_NUM_OF_BAD_BLOCKS		(20U)

#if (RZA_NAND_READ_UNIT_128BLOCK == 1)
#define SPI_NAND_NUM_OF_ONCE_TRANS_BLOCKS	(128U)
#endif /* (RZA_NAND_READ_UNIT_128BLOCK == 1) */

#ifdef __cplusplus
}
#endif

#endif /* __SPI_NAND_W25N01GVZEIG_H__ */
